[tool.kedro]
package_name = "exemplo_kedro_iris2"
project_name = "exemplo_kedro_iris2"
kedro_init_version = "0.18.9"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/exemplo_kedro_iris2 -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
