### Parâmetros data_engineering pipeline
concatenacao:  'usado_apenas_para_ilustrar_o_exemplo'

### Parâmetros model_training pipeline
feature_list: ['sepal_length','sepal_width','petal_length','petal_width','sepal_area','petal_area']
target:        'species'
k_neighbors:   5
